name: Terraform Module Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Terraform Validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate PR title version
        if: github.event_name == 'pull_request'
        run: |
          echo "Checking PR title: ${{ github.event.pull_request.title }}"
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+\  ]]; then
            echo "❌ PR title must start with a version, e.g., 'v1.2.3 - Your message'"
            exit 1
          fi

      - name: Set up Python (for pre-commit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.7

      - name: Run Pre-Commit Hooks
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.9.0
        with:
          terraform-version: 1.3.7
          terraform-docs-version: v0.19.0
          args: "--all-files --color always --show-diff-on-failure"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
